#!/bin/sh
# Rebuilds the Rigveda pack from its sources and every translation we hold.
#
# The pack is generated, not edited: the Devanagari comes from the source
# files, the transliteration is derived from that Devanagari, and the
# translations are merged in from the response files. So this can be run at
# any time and is the only way the content JSON should ever change.
set -e
cd "$(dirname "$0")/.."
PACK=content/rigveda.sa

python3 tool/rigveda_to_json.py $PACK

# Translations that came back from Gemini, before we began doing them here.
dart run tool/merge_translations.dart $PACK/content.json $PACK/responses/*.json \
  --out $PACK/content.json \
  --licence rigveda-ai \
  --licence-name 'Translations, machine-generated' \
  --licence-attribution 'Translations generated by an AI model.' \
  --origin machine --translator Gemini

# Translations written in this repo.
if ls $PACK/translations/*.json >/dev/null 2>&1; then
  dart run tool/merge_translations.dart $PACK/content.json $PACK/translations/*.json \
    --out $PACK/content.json \
    --licence rigveda-ai --origin machine --translator Claude
fi

# The transliteration is mechanical, so it is derived last, over everything.
dart run tool/derive_iast.dart $PACK/content.json
